global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8080']

  - job_name: 'mlflow'
    metrics_path: /metrics
    static_configs:
      - targets: ['mlflow:5001']
